In [1]:
import json
import numpy as np
import pandas as pd
from westpy.qdet import QDETResult

effective_hamiltonian = QDETResult(filename='../pdep_4992.wfreq.save/wfreq.json')
#let M=0
occ=effective_hamiltonian.__dict__['occupation']
print("occ: ", occ)
nelec = (int(occ.sum()/2),int(occ.sum()/2))
# diagonalize Hamiltonian
solution = effective_hamiltonian.solve(nroots = 50, nelec=nelec)

 _    _ _____ _____ _____
| |  | |  ___/  ___|_   _|
| |  | | |__ \ `--.  | |_ __  _   _
| |/\| |  __| `--. \ | | '_ \| | | |
\  /\  / |___/\__/ / | | |_) | |_| |
 \/  \/\____/\____/  \_/ .__/ \__, |
                       | |     __/ |
                       |_|    |___/

WEST version     :  6.0.0
Today            :  2024-12-28 19:10:56.147298
occ:  [[1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
-----------------------------------------------------
===============================================================
Building effective Hamiltonian...
nspin: 2
occupations: [[1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
===============================================================

               diag[1RDM - 1RDM(GS)]                                           \
   E [eV] char                  1240   1241   1242   1243   1244  1246   1247
0   0.000   3-                 0.000  0.000  0.000  0.000  0.000 0.000  0.000
1   0.113   2-                 0.008 -0.020 -0.010 -0.024 -0.001 0.000  0.015
2   0.114   2-                 0.008 -0.016 -0.003 -0.035 -0.001 0.000  0.019
3   0.187   2-                 0.012 -0.003 -0.031 -0.054 -0.001 0.001  0.033
4   0.329   2-                 0.043 -0.209  0.089 -0.186  0.265 0.163 -0.052
5   0.329   2-                 0.043  0.273 -0.393 -0.185  0.265 0.163 -0.052
6   0.883   2-                 0.063 -0.279 -0.391  0.507  0.200 0.002 -0.049
7   0.885   2-                 0.063 -0.270  0.044  0.063  0.200 0.002 -0.023
8   0.930   2-                 0.066  0.119  0.067 -0.168  0.005 0.082 -0.051
9   0.930   2-                 0.066  0.558 -0.367 -0.174  0.005 0.083 -0.051
10  1.380   3-                -0.441  0.111  0.157  0.026  0.001 0.002 -0.009
11  1.383   3-                -0.441  0.197  0.209 -0.113  0.001 0.002  0.097
12  1.475   4-                -0.368  0.051  0.046  0.029  0.202 0.102 -0.025
13  1.497   3-                -0.402  0.025  0.056  0.091  0.206 0.105 -0.028
14  1.619   3-                -0.117  0.065 -0.033 -0.063  0.046 0.002  0.001
15  1.635   3-                -0.429 -0.137  0.274  0.067 -0.003 0.001  0.052
16  1.636   3-                -0.429  0.154  0.012  0.040 -0.003 0.002  0.096
17  1.709   3-                -0.369 -0.039  0.017  0.222  0.158 0.001 -0.003
18  1.709   3-                -0.369 -0.039  0.018  0.221  0.158 0.001 -0.003
19  1.828   3-                -0.380 -0.040 -0.004  0.217  0.172 0.002  0.010
20  1.840   3-                -0.423  0.076  0.043 -0.065  0.254 0.197 -0.025
21  1.881   3-                -0.390 -0.041  0.011 -0.018  0.255 0.182  0.004
22  1.881   3-                -0.390 -0.043  0.020 -0.025  0.255 0.180  0.007
23  1.901   2-                -0.094  0.049 -0.046 -0.073  0.046 0.004 -0.016
24  1.901   2-                -0.093  0.039 -0.048 -0.061  0.045 0.004 -0.018
25  1.987   3-                -0.404 -0.021 -0.011 -0.039  0.264 0.182  0.022
26  1.995   3-                -0.385  0.547  0.080 -0.164  0.020 0.043 -0.046
27  2.065   2-                -0.047 -0.010 -0.068 -0.069  0.034 0.016 -0.023
28  2.097   3-                -0.099 -0.249 -0.172  0.111  0.046 0.187  0.181
29  2.121   2-                 0.075 -0.269 -0.388  0.003  0.545 0.180 -0.051
30  2.200   2-                 0.011 -0.256 -0.246 -0.004 -0.004 0.240  0.246
31  2.200   2-                 0.011 -0.256 -0.239 -0.010 -0.004 0.240  0.246
32  2.227   3-                -0.307 -0.279 -0.031  0.355  0.151 0.056  0.064
33  2.274   2-                 0.005 -0.238 -0.225 -0.023 -0.003 0.241  0.224
34  2.452   2-                 0.044 -0.210 -0.393 -0.183  0.261 0.179  0.410
35  2.452   2-                 0.044 -0.207 -0.396 -0.183  0.261 0.618 -0.029
36  2.491   3-                -0.360  0.308  0.019 -0.017  0.007 0.067 -0.006
37  2.531   2-                 0.044 -0.279 -0.380  0.199  0.228 0.007 -0.040
38  2.533   2-                 0.043 -0.264 -0.220  0.022  0.229 0.010  0.174
39  2.539   2-                 0.082  0.146 -0.388  0.020  0.233 0.043 -0.047
40  2.590   3-                -0.196 -0.245 -0.166  0.216  0.304 0.122 -0.046
41  2.592   3-                -0.205 -0.025 -0.212  0.049  0.309 0.127 -0.003
42  2.597   3-                -0.338  0.257 -0.002 -0.030  0.013 0.069  0.014
43  2.597   3-                -0.338  0.257  0.001 -0.032  0.012 0.068  0.015
44  2.629   3-                -0.152 -0.268 -0.187  0.184  0.278 0.105 -0.047
45  2.630   3-                -0.141 -0.078 -0.267  0.070  0.271 0.101  0.077
46  2.696   3-                -0.329  0.262 -0.026 -0.051  0.017 0.066  0.024
47  2.895   3-                -0.432 -0.085  0.264 -0.102  0.005 0.012  0.076
48  2.901   3-                -0.432 -0.008 -0.103  0.188  0.006 0.010  0.032
49  2.937   2-                -0.374  0.148  0.052 -0.083  0.232 0.165 -0.038


     1248   1249   1250   1255   1256   1257
0   0.000  0.000  0.000  0.000  0.000  0.000
1   0.018  0.007  0.006 -0.000  0.000  0.000
2   0.013  0.006  0.007 -0.000  0.000  0.000
3   0.023  0.009  0.012 -0.000  0.001  0.001
4  -0.055 -0.033 -0.032  0.008 -0.001 -0.001
5  -0.055 -0.033 -0.032  0.008 -0.001 -0.001
6   0.005 -0.026 -0.029 -0.000 -0.001 -0.001
7  -0.021 -0.030 -0.025 -0.000 -0.001 -0.000
8  -0.054 -0.033 -0.031 -0.000 -0.001 -0.001
9  -0.054 -0.032 -0.032 -0.000 -0.001 -0.001
10  0.093  0.053  0.006 -0.000  0.002 -0.000
11 -0.013  0.005  0.053 -0.000 -0.001  0.002
12 -0.022 -0.014 -0.012  0.005  0.003  0.003
13 -0.020 -0.020 -0.019  0.005  0.001  0.001
14  0.001  0.029  0.035  0.001  0.015  0.019
15  0.092  0.046  0.034  0.000  0.002  0.001
16  0.047  0.033  0.047  0.000  0.001  0.001
17  0.014 -0.006 -0.004 -0.000  0.004  0.005
18  0.015 -0.005 -0.005 -0.000  0.005  0.004
19  0.028 -0.008 -0.005 -0.000  0.003  0.005
20 -0.026 -0.020 -0.019  0.010 -0.001 -0.000
21  0.002 -0.008 -0.007  0.008  0.001  0.002
22  0.000 -0.008 -0.007  0.008  0.001  0.001
23 -0.018  0.039  0.050  0.001  0.025  0.032
24 -0.016  0.045  0.044  0.001  0.028  0.029
25  0.015 -0.008 -0.007  0.008 -0.001 -0.000
26 -0.046 -0.026 -0.026  0.001  0.001  0.001
27 -0.030  0.063  0.052  0.000  0.043  0.039
28  0.006 -0.006 -0.006  0.000  0.001  0.001
29 -0.035 -0.032 -0.031  0.004 -0.000  0.000
30  0.001  0.005  0.004  0.000  0.001  0.001
31  0.000  0.004  0.005  0.000  0.001  0.001
32  0.015 -0.014 -0.012 -0.000 -0.000 -0.000
33 -0.007  0.010  0.012  0.000  0.002  0.002
34 -0.053 -0.032 -0.029  0.008 -0.001 -0.000
35 -0.054 -0.030 -0.031  0.008 -0.000 -0.000
36  0.002 -0.010 -0.010  0.000 -0.000 -0.000
37  0.228 -0.000 -0.009  0.001  0.002 -0.000
38  0.013 -0.010  0.002  0.001 -0.000  0.002
39 -0.028 -0.031 -0.030 -0.000 -0.000 -0.000
40  0.059 -0.022 -0.027  0.003 -0.000 -0.000
41  0.008 -0.028 -0.022  0.003 -0.001  0.000
42  0.021 -0.004 -0.001 -0.000  0.001  0.001
43  0.021 -0.002 -0.003 -0.000  0.001  0.001
44  0.121 -0.018 -0.021  0.003  0.001 -0.000
45  0.001 -0.021 -0.017  0.003 -0.000  0.001
46  0.028  0.002  0.003 -0.000  0.002  0.003
47  0.018  0.022  0.161  0.000  0.007  0.053
48  0.068  0.158  0.025  0.000  0.049  0.008
49 -0.043 -0.032 -0.030  0.005 -0.000 -0.000

-----------------------------------------------------

In [15]:
solution.keys()
solution['nelec']

(2, 2)

In [21]:
#np.shape(solution['evcs'][0])
from westpy.qdet import visualize_correlated_state
for i, state in enumerate(solution['evcs']):
    en = solution['evs'][i]
    print(f'i= {i}, en [eV]={en} Deter')
    multiwfc=visualize_correlated_state(state, solution['norb'], solution['nelec'], cutoff=10 **(-1))
    print(multiwfc)

i= 0, en [eV]=0.0 Deter
+0.173|0000000000011>|0000000000101>+0.469|0000000000011>|0000000001001>+0.188|0000000000011>|0000000001010>-0.305|0000000000011>|0000010000001>-0.154|0000000000011>|0000100000001>-0.186|0000000000011>|0001000000001>-0.456|0000000000101>|0000000000101>-0.183|0000000000101>|0000000000110>+0.178|0000000000101>|0000000001001>-0.298|0000000000101>|0000001000001>-0.184|0000000000101>|0000100000001>+0.146|0000000000101>|0001000000001>-0.146|0000000001010>|0000000001001>+0.142|0000000001100>|0000000000101>
i= 1, en [eV]=0.11345677261327157 Deter
-0.433|0000000000011>|0000000000101>-0.168|0000000000011>|0000000000110>-0.137|0000000000011>|0000000001001>-0.262|0000000000011>|0000001000001>+0.209|0000000000011>|0000010000001>+0.249|0000000000011>|0001000000001>-0.128|0000000000101>|0000000000101>+0.453|0000000000101>|0000000001001>+0.176|0000000000101>|0000000001010>-0.208|0000000000101>|0000001000001>-0.281|0000000000101>|0000010000001>-0.258|0000000000101>|0000100000001>+0.129|0000000001010>|0000000000101>-0.134|0000000001100>|0000000001001>
i= 2, en [eV]=0.11353795774060667 Deter
-0.135|0000000000011>|0000000000101>+0.436|0000000000011>|0000000001001>+0.170|0000000000011>|0000000001010>-0.209|0000000000011>|0000001000001>-0.267|0000000000011>|0000010000001>-0.251|0000000000011>|0000100000001>+0.450|0000000000101>|0000000000101>+0.175|0000000000101>|0000000000110>+0.130|0000000000101>|0000000001001>+0.276|0000000000101>|0000001000001>-0.208|0000000000101>|0000010000001>-0.255|0000000000101>|0001000000001>-0.129|0000000001010>|0000000001001>-0.134|0000000001100>|0000000000101>
i= 3, en [eV]=0.18747652515391014 Deter
-0.421|0000000000011>|0000000000101>-0.160|0000000000011>|0000000000110>+0.152|0000000000011>|0000000001001>-0.374|0000000000011>|0000001000001>-0.122|0000000000011>|0000001000010>-0.213|0000000000011>|0000100000001>+0.178|0000000000011>|0001000000001>-0.159|0000000000101>|0000000000101>-0.398|0000000000101>|0000000001001>-0.151|0000000000101>|0000000001010>+0.360|0000000000101>|0000010000001>+0.117|0000000000101>|0000010000010>+0.165|0000000000101>|0000100000001>+0.210|0000000000101>|0001000000001>+0.121|0000000001010>|0000000000101>+0.114|0000000001100>|0000000001001>
i= 4, en [eV]=0.32938596518146646 Deter
+0.327|0000000000101>|0000000000011>+0.674|0000000000101>|0000000010001>+0.233|0000000000101>|0000000010010>-0.530|0000000000101>|0000000100001>-0.118|0000000000101>|0000000100010>+0.110|0000000000101>|0000000110000>+0.123|0000000000101>|0010000000001>-0.116|0000000001100>|0000000010001>
i= 5, en [eV]=0.32949414808842475 Deter
-0.327|0000000000011>|0000000000011>-0.674|0000000000011>|0000000010001>-0.233|0000000000011>|0000000010010>+0.530|0000000000011>|0000000100001>+0.118|0000000000011>|0000000100010>-0.110|0000000000011>|0000000110000>-0.123|0000000000011>|0010000000001>+0.116|0000000001010>|0000000010001>
i= 6, en [eV]=0.8828360444214474 Deter
+0.112|0000000000101>|0000000000011>+0.655|0000000001001>|0000000001001>+0.137|0000000001001>|0000000001010>-0.162|0000000001001>|0000010000001>+0.574|0000000010001>|0000000001001>+0.142|0000000010001>|0000000001010>-0.166|0000000010001>|0000010000001>+0.140|0000000011000>|0000000001001>-0.224|0000010000001>|0000000001001>
i= 7, en [eV]=0.8854261731364297 Deter
+0.119|0000000000011>|0000000000011>+0.654|0000000001001>|0000000000101>+0.136|0000000001001>|0000000000110>+0.162|0000000001001>|0000001000001>+0.573|0000000010001>|0000000000101>+0.141|0000000010001>|0000000000110>+0.166|0000000010001>|0000001000001>+0.140|0000000011000>|0000000000101>-0.224|0000010000001>|0000000000101>
i= 8, en [eV]=0.929764514634602 Deter
-0.181|0000000000011>|0000000000011>+0.843|0000000000101>|0000000000011>-0.127|0000000000101>|0000000010001>+0.363|0000000000101>|0000000100001>+0.126|0000000000101>|0000000100010>-0.160|0000000001100>|0000000000011>
i= 9, en [eV]=0.9299091696899071 Deter
+0.842|0000000000011>|0000000000011>-0.127|0000000000011>|0000000010001>+0.363|0000000000011>|0000000100001>+0.125|0000000000011>|0000000100010>+0.181|0000000000101>|0000000000011>-0.160|0000000001010>|0000000000011>
i= 10, en [eV]=1.3796048663762508 Deter
-0.245|0000000000101>|0000000001100>+0.134|0000000000101>|0000001001000>+0.195|0000000000101>|0000010000100>+0.111|0000000000101>|0000011000000>+0.141|0000000000101>|0000100000100>-0.105|0000000000101>|0001000001000>-0.518|0000000000110>|0000000001001>-0.171|0000000000110>|0000000001010>-0.129|0000000000110>|0000000011000>+0.167|0000000000110>|0000001000001>+0.443|0000000000110>|0000010000001>+0.126|0000000000110>|0000010000010>+0.339|0000000000110>|0000100000001>+0.199|0000000000110>|0001000000001>
i= 11, en [eV]=1.383004000216461 Deter
-0.247|0000000000011>|0000000001100>+0.197|0000000000011>|0000001001000>+0.136|0000000000011>|0000010000100>+0.112|0000000000011>|0000011000000>+0.107|0000000000011>|0000100000100>-0.142|0000000000011>|0001000001000>-0.517|0000000000110>|0000000000101>-0.171|0000000000110>|0000000000110>-0.128|0000000000110>|0000000010100>-0.442|0000000000110>|0000001000001>-0.126|0000000000110>|0000001000010>+0.166|0000000000110>|0000010000001>-0.198|0000000000110>|0000100000001>+0.337|0000000000110>|0001000000001>
i= 12, en [eV]=1.4752980508574312 Deter
-0.198|0000000000011>|0000000011000>+0.139|0000000000011>|0000000101000>-0.130|0000000000011>|0000010000001>-0.120|0000000000011>|0001000000001>+0.198|0000000000101>|0000000010100>-0.139|0000000000101>|0000000100100>-0.130|0000000000101>|0000001000001>-0.120|0000000000101>|0000100000001>+0.416|0000000000110>|0000000010001>+0.112|0000000000110>|0000000010010>-0.356|0000000000110>|0000000100001>+0.102|0000000000110>|0000000110000>+0.104|0000000001001>|0000000001100>+0.104|0000000001010>|0000000000101>+0.272|0000000001010>|0000000001001>-0.272|0000000001100>|0000000000101>+0.103|0000000001100>|0000000001001>+0.182|0000000010010>|0000000001001>-0.107|0000000010010>|0000010000001>-0.181|0000000010100>|0000000000101>-0.107|0000000010100>|0000001000001>
i= 13, en [eV]=1.4971044226461856 Deter
-0.151|0000000000011>|0000000011000>+0.154|0000000000011>|0000000101000>+0.150|0000000000101>|0000000010100>-0.153|0000000000101>|0000000100100>+0.384|0000000000110>|0000000010001>+0.103|0000000000110>|0000000010010>-0.350|0000000000110>|0000000100001>-0.125|0000000001001>|0000000001100>-0.120|0000000001010>|0000000000101>-0.315|0000000001010>|0000000001001>+0.109|0000000001010>|0000010000001>+0.314|0000000001100>|0000000000101>-0.119|0000000001100>|0000000001001>+0.108|0000000001100>|0000001000001>-0.104|0000000010001>|0000000001100>-0.227|0000000010010>|0000000001001>+0.116|0000000010010>|0000010000001>+0.226|0000000010100>|0000000000101>+0.116|0000000010100>|0000001000001>
i= 14, en [eV]=1.619494441054267 Deter
-0.236|0000000000011>|0000000001001>-0.250|0000000000011>|0000000001010>-0.273|0000000000011>|0000010000001>-0.197|0000000000011>|0000100000001>-0.257|0000000000011>|0001000000001>-0.146|0000000000011>|0100000000001>+0.247|0000000000101>|0000000000101>+0.253|0000000000101>|0000000000110>-0.278|0000000000101>|0000001000001>-0.256|0000000000101>|0000100000001>+0.219|0000000000101>|0001000000001>+0.162|0000000000101>|1000000000001>-0.240|0000000000110>|0000000000011>+0.126|0000000001010>|0000010000001>+0.122|0000000001100>|0000001000001>-0.186|0000000010010>|0000000001001>+0.177|0000000010100>|0000000000101>
i= 15, en [eV]=1.63496173152323 Deter
-0.146|0000000000011>|0000000001100>+0.104|0000000000011>|0000001001000>+0.105|0000000000011>|0000010000100>+0.417|0000000000101>|0000000001100>-0.113|0000000000101>|0000001000100>-0.279|0000000000101>|0000001001000>-0.321|0000000000101>|0000010000100>+0.114|0000000000101>|0000010001000>-0.219|0000000000101>|0000011000000>-0.225|0000000000101>|0000100000100>-0.119|0000000000101>|0000100001000>+0.124|0000000000101>|0000110000000>-0.138|0000000000101>|0001000000100>+0.210|0000000000101>|0001000001000>-0.119|0000000000101>|0001001000000>-0.101|0000000000101>|0001010000000>-0.103|0000000000101>|0001100000000>-0.286|0000000000110>|0000000001001>-0.108|0000000000110>|0000000001010>+0.246|0000000000110>|0000010000001>+0.186|0000000000110>|0000100000001>+0.114|0000000000110>|0001000000001>-0.110|0000000001100>|0000000001100>
i= 16, en [eV]=1.6361093791262626 Deter
+0.416|0000000000011>|0000000001100>-0.114|0000000000011>|0000001000100>-0.319|0000000000011>|0000001001000>-0.279|0000000000011>|0000010000100>+0.113|0000000000011>|0000010001000>-0.218|0000000000011>|0000011000000>-0.210|0000000000011>|0000100000100>-0.137|0000000000011>|0000100001000>-0.101|0000000000011>|0000101000000>+0.118|0000000000011>|0000110000000>-0.119|0000000000011>|0001000000100>+0.223|0000000000011>|0001000001000>-0.124|0000000000011>|0001001000000>-0.103|0000000000011>|0001100000000>+0.146|0000000000101>|0000000001100>-0.105|0000000000101>|0000001001000>-0.104|0000000000101>|0000010000100>-0.289|0000000000110>|0000000000101>-0.109|0000000000110>|0000000000110>-0.249|0000000000110>|0000001000001>-0.115|0000000000110>|0000100000001>+0.187|0000000000110>|0001000000001>-0.109|0000000001010>|0000000001100>
i= 17, en [eV]=1.7090878524042425 Deter
+0.157|0000000000011>|0001000000001>-0.154|0000000000101>|0000100000001>-0.395|0000000001010>|0000000000101>-0.189|0000000001010>|0000000001001>-0.133|0000000001010>|0000001000001>+0.140|0000000001010>|0000010000001>-0.191|0000000001100>|0000000000101>+0.394|0000000001100>|0000000001001>-0.140|0000000001100>|0000001000001>-0.133|0000000001100>|0000010000001>-0.282|0000000010010>|0000000000101>-0.136|0000000010010>|0000000001001>-0.135|0000000010010>|0000001000001>+0.142|0000000010010>|0000010000001>+0.121|0000000010010>|0001000000001>-0.136|0000000010100>|0000000000101>+0.283|0000000010100>|0000000001001>-0.142|0000000010100>|0000001000001>-0.134|0000000010100>|0000010000001>-0.121|0000000010100>|0000100000001>+0.105|0000010000010>|0000000000101>-0.105|0000010000100>|0000000001001>
i= 18, en [eV]=1.7091697478385917 Deter
-0.159|0000000000011>|0000100000001>-0.151|0000000000101>|0001000000001>-0.189|0000000001010>|0000000000101>+0.393|0000000001010>|0000000001001>-0.140|0000000001010>|0000001000001>-0.130|0000000001010>|0000010000001>+0.395|0000000001100>|0000000000101>+0.191|0000000001100>|0000000001001>+0.136|0000000001100>|0000001000001>-0.141|0000000001100>|0000010000001>-0.137|0000000010010>|0000000000101>+0.278|0000000010010>|0000000001001>-0.141|0000000010010>|0000001000001>-0.134|0000000010010>|0000010000001>-0.121|0000000010010>|0000100000001>+0.287|0000000010100>|0000000000101>+0.136|0000000010100>|0000000001001>+0.135|0000000010100>|0000001000001>-0.143|0000000010100>|0000010000001>-0.122|0000000010100>|0001000000001>-0.103|0000010000010>|0000000001001>-0.106|0000010000100>|0000000000101>
i= 19, en [eV]=1.828480178645554 Deter
+0.105|0000000000011>|0000100000001>-0.101|0000000000011>|0001000000001>-0.105|0000000000101>|0001000000001>+0.388|0000000001010>|0000000000101>-0.151|0000000001010>|0000000001001>+0.233|0000000001010>|0000001000001>+0.145|0000000001100>|0000000000101>+0.391|0000000001100>|0000000001001>-0.238|0000000001100>|0000010000001>+0.284|0000000010010>|0000000000101>-0.116|0000000010010>|0000000001001>+0.219|0000000010010>|0000001000001>+0.102|0000000010010>|0000100000001>+0.105|0000000010100>|0000000000101>+0.297|0000000010100>|0000000001001>-0.221|0000000010100>|0000010000001>-0.101|0000000010100>|0001000000001>-0.105|0000010000010>|0000000000101>-0.110|0000010000100>|0000000001001>
i= 20, en [eV]=1.8401758584054824 Deter
+0.137|0000000000011>|0000000001010>-0.123|0000000000011>|0000000010100>-0.334|0000000000011>|0000000011000>+0.263|0000000000011>|0000000101000>-0.170|0000000000011>|0000010010000>+0.139|0000000000011>|0000010100000>-0.128|0000000000101>|0000000000110>+0.319|0000000000101>|0000000010100>-0.125|0000000000101>|0000000011000>-0.251|0000000000101>|0000000100100>-0.162|0000000000101>|0000001010000>+0.132|0000000000101>|0000001100000>-0.391|0000000000110>|0000000010001>-0.103|0000000000110>|0000000010010>+0.388|0000000000110>|0000000100001>+0.100|0000000000110>|0000000100010>-0.118|0000000000110>|0000000110000>
i= 21, en [eV]=1.8809773102612264 Deter
-0.388|0000000000011>|0000000010100>-0.132|0000000000011>|0000000011000>+0.316|0000000000011>|0000000100100>+0.108|0000000000011>|0000000101000>+0.172|0000000000011>|0000001010000>-0.152|0000000000011>|0000001100000>-0.144|0000000000011>|0000010010000>+0.126|0000000000011>|0000010100000>-0.125|0000000000011>|0001000010000>+0.120|0000000000011>|0001000100000>-0.132|0000000000101>|0000000010100>+0.395|0000000000101>|0000000011000>+0.108|0000000000101>|0000000100100>-0.322|0000000000101>|0000000101000>+0.145|0000000000101>|0000001010000>-0.127|0000000000101>|0000001100000>+0.178|0000000000101>|0000010010000>-0.156|0000000000101>|0000010100000>+0.129|0000000000101>|0000100010000>-0.122|0000000000101>|0000100100000>
i= 22, en [eV]=1.881016879659575 Deter
-0.134|0000000000011>|0000000010100>+0.386|0000000000011>|0000000011000>+0.109|0000000000011>|0000000100100>-0.315|0000000000011>|0000000101000>+0.144|0000000000011>|0000001010000>-0.126|0000000000011>|0000001100000>+0.172|0000000000011>|0000010010000>-0.152|0000000000011>|0000010100000>+0.126|0000000000011>|0000100010000>-0.120|0000000000011>|0000100100000>+0.397|0000000000101>|0000000010100>+0.131|0000000000101>|0000000011000>-0.323|0000000000101>|0000000100100>-0.107|0000000000101>|0000000101000>-0.178|0000000000101>|0000001010000>+0.156|0000000000101>|0000001100000>+0.145|0000000000101>|0000010010000>-0.127|0000000000101>|0000010100000>+0.128|0000000000101>|0001000010000>-0.122|0000000000101>|0001000100000>
i= 23, en [eV]=1.9009806042642718 Deter
-0.244|0000000000011>|0000000000101>-0.242|0000000000011>|0000000000110>-0.170|0000000000011>|0000000001001>-0.169|0000000000011>|0000000001010>+0.110|0000000000011>|0000001000001>-0.168|0000000000011>|0000010000001>-0.364|0000000000011>|0001000000001>+0.103|0000000000011>|0001000010000>-0.102|0000000000011>|0100000000001>-0.214|0000000000011>|1000000000001>-0.178|0000000000101>|0000000000101>-0.177|0000000000101>|0000000000110>+0.222|0000000000101>|0000000001001>+0.221|0000000000101>|0000000001010>+0.168|0000000000101>|0000001000001>+0.104|0000000000101>|0000010000001>+0.345|0000000000101>|0000100000001>+0.190|0000000000101>|0100000000001>-0.115|0000000000101>|1000000000001>+0.106|0000000001010>|0001000000001>-0.156|0000000010010>|0000000000101>-0.110|0000000010100>|0000000000101>+0.120|0000000010100>|0000000001001>
i= 24, en [eV]=1.9012983885987305 Deter
-0.174|0000000000011>|0000000000101>-0.171|0000000000011>|0000000000110>+0.236|0000000000011>|0000000001001>+0.236|0000000000011>|0000000001010>+0.169|0000000000011>|0000001000001>+0.115|0000000000011>|0000010000001>+0.358|0000000000011>|0000100000001>-0.100|0000000000011>|0000100010000>+0.201|0000000000011>|0100000000001>-0.110|0000000000011>|1000000000001>+0.231|0000000000101>|0000000000101>+0.227|0000000000101>|0000000000110>+0.175|0000000000101>|0000000001001>+0.175|0000000000101>|0000000001010>+0.169|0000000000101>|0000010000001>+0.353|0000000000101>|0001000000001>-0.102|0000000000101>|0001000010000>+0.108|0000000000101>|0100000000001>+0.204|0000000000101>|1000000000001>-0.101|0000000001010>|0000100000001>-0.104|0000000010010>|0000000000101>+0.139|0000000010010>|0000000001001>+0.137|0000000010100>|0000000000101>+0.102|0000000010100>|0000000001001>
i= 25, en [eV]=1.987172890708306 Deter
-0.139|0000000000011>|0000000000110>+0.364|0000000000011>|0000000010100>-0.136|0000000000011>|0000000011000>-0.300|0000000000011>|0000000100100>+0.112|0000000000011>|0000000101000>-0.109|0000000000011>|0000001000010>-0.274|0000000000011>|0000001010000>+0.224|0000000000011>|0000001100000>-0.125|0000000000011>|0000100010000>+0.102|0000000000011>|0000100100000>+0.102|0000000000011>|0001000010000>-0.134|0000000000101>|0000000001010>+0.137|0000000000101>|0000000010100>+0.356|0000000000101>|0000000011000>-0.113|0000000000101>|0000000100100>-0.293|0000000000101>|0000000101000>+0.108|0000000000101>|0000010000010>+0.270|0000000000101>|0000010010000>-0.221|0000000000101>|0000010100000>+0.124|0000000000101>|0001000010000>-0.101|0000000000101>|0001000100000>
i= 26, en [eV]=1.9948241214900448 Deter
+0.144|0000000000011>|0000000001001>-0.133|0000000000101>|0000000000101>-0.855|0000000000110>|0000000000011>-0.197|0000000000110>|0000000010010>-0.209|0000000000110>|0000000100001>-0.111|0000000000110>|0000000100010>
i= 27, en [eV]=2.0654472443942318 Deter
+0.251|0000000000011>|0000000000101>+0.214|0000000000011>|0000000000110>-0.110|0000000000011>|0000000001001>-0.127|0000000000011>|0000001000001>-0.308|0000000000011>|0000100000001>+0.229|0000000000011>|0001000000001>-0.137|0000000000011>|0100000000001>+0.231|0000000000011>|1000000000001>+0.277|0000000000101>|0000000001001>+0.240|0000000000101>|0000000001010>+0.143|0000000000101>|0000010000001>+0.267|0000000000101>|0000100000001>+0.304|0000000000101>|0001000000001>+0.245|0000000000101>|0100000000001>+0.130|0000000000101>|1000000000001>+0.130|0000000010010>|0000000000101>+0.140|0000000010100>|0000000001001>
i= 28, en [eV]=2.0974831225417323 Deter
-0.106|0000000000110>|0000000000011>-0.265|0000000001001>|0000000001100>-0.253|0000000010001>|0000000001100>+0.199|0000000100001>|0000000000101>+0.384|0000000100001>|0000000001001>+0.145|0000000100001>|0000000001010>-0.268|0000000100001>|0000010000001>-0.103|0000000100001>|0000100000001>-0.161|0000000100001>|0001000000001>+0.131|0000000101000>|0000000001001>-0.372|0000001000001>|0000000000101>-0.140|0000001000001>|0000000000110>+0.206|0000001000001>|0000000001001>-0.263|0000001000001>|0000001000001>-0.161|0000001000001>|0000100000001>-0.128|0000001001000>|0000000000101>
i= 29, en [eV]=2.120853836660004 Deter
+0.121|0000000001001>|0000000000011>+0.474|0000000001001>|0000000010001>-0.369|0000000001001>|0000000100001>+0.153|0000000010001>|0000000000011>+0.546|0000000010001>|0000000010001>+0.105|0000000010001>|0000000010010>-0.440|0000000010001>|0000000100001>-0.147|0000010000001>|0000000010001>+0.120|0000010000001>|0000000100001>
i= 30, en [eV]=2.200203343702532 Deter
+0.349|0000000100001>|0000000000101>+0.132|0000000100001>|0000000000110>+0.341|0000000100001>|0000000001001>+0.130|0000000100001>|0000000001010>+0.127|0000000100001>|0000001000001>-0.275|0000000100001>|0000010000001>-0.232|0000000100001>|0001000000001>+0.100|0000000101000>|0000000000101>+0.329|0000001000001>|0000000000101>+0.125|0000001000001>|0000000000110>-0.370|0000001000001>|0000000001001>-0.140|0000001000001>|0000000001010>+0.272|0000001000001>|0000001000001>+0.142|0000001000001>|0000010000001>+0.238|0000001000001>|0000100000001>-0.107|0000001001000>|0000000001001>
i= 31, en [eV]=2.200220250584037 Deter
-0.331|0000000100001>|0000000000101>-0.126|0000000100001>|0000000000110>+0.358|0000000100001>|0000000001001>+0.136|0000000100001>|0000000001010>-0.271|0000000100001>|0000001000001>-0.135|0000000100001>|0000010000001>-0.234|0000000100001>|0000100000001>+0.102|0000000101000>|0000000001001>+0.360|0000001000001>|0000000000101>+0.137|0000001000001>|0000000000110>+0.339|0000001000001>|0000000001001>+0.129|0000001000001>|0000000001010>+0.134|0000001000001>|0000001000001>-0.276|0000001000001>|0000010000001>-0.236|0000001000001>|0001000000001>+0.105|0000001001000>|0000000000101>
i= 32, en [eV]=2.2270183215044437 Deter
+0.522|0000000001001>|0000000001100>-0.169|0000000001001>|0000001001000>-0.169|0000000001001>|0000010000100>+0.439|0000000010001>|0000000001100>-0.159|0000000010001>|0000001001000>-0.159|0000000010001>|0000010000100>+0.153|0000000011000>|0000000001100>+0.122|0000000100001>|0000000000101>+0.202|0000000100001>|0000000001001>-0.151|0000000100001>|0000010000001>-0.228|0000001000001>|0000000000101>+0.108|0000001000001>|0000000001001>-0.162|0000001000001>|0000001000001>-0.162|0000010000001>|0000000001100>
i= 33, en [eV]=2.274155735701784 Deter

In [2]:
solution2 = effective_hamiltonian.solve(nroots = 50, nelec=(3,1))

-----------------------------------------------------
===============================================================
Building effective Hamiltonian...
nspin: 2
occupations: [[1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
===============================================================

               diag[1RDM - 1RDM(GS)]                                     \
   E [eV] char                  1240   1241   1242   1243   1244   1246
0   0.000   3-                 0.000  0.000  0.000  0.000  0.000  0.000
1   0.208   3-                 0.099 -0.536 -0.009  0.243  0.184 -0.001
2   0.208   3-                 0.099 -0.063 -0.483  0.243  0.184 -0.001
3   1.352   4-                -0.370 -0.161 -0.021  0.323  0.167  0.006
4   1.484   4-                -0.382 -0.082 -0.002  0.167 -0.017  0.001
5   1.489   4-                -0.382 -0.081  0.182 -0.017 -0.017  0.001
6   1.504   4-                -0.376 -0.047 -0.002 -0.024  0.239  0.197
7   1.688   3-                -0.373 -0.182 -0.061  0.360  0.166  0.002
8   1.704   4-                -0.353 -0.329 -0.081  0.411  0.174  0.005
9   1.704   4-                -0.353 -0.341 -0.056  0.397  0.174  0.004
10  1.805   4-                -0.326 -0.318 -0.111  0.358  0.161  0.022
11  1.920   3-                 0.056 -0.328 -0.189  0.095  0.057  0.102
12  1.920   3-                 0.055 -0.223 -0.294  0.095  0.057  0.096
13  1.924   3-                -0.010 -0.252 -0.242  0.027  0.006  0.217
14  1.999   3-                 0.004 -0.235 -0.235 -0.002 -0.007  0.226
15  2.068   3-                 0.058 -0.294 -0.222  0.062  0.028  0.121
16  2.068   3-                 0.058 -0.246 -0.270  0.061  0.028  0.121
17  2.222   3-                -0.293  0.229 -0.012 -0.018  0.002  0.064
18  2.325   3-                 0.104 -0.548 -0.490  0.235  0.183  0.031
19  2.325   3-                 0.104 -0.546 -0.492  0.235  0.183  0.458
20  2.439   4-                -0.344 -0.567 -0.005  0.212  0.464  0.226
21  2.439   4-                -0.344 -0.084 -0.489  0.212  0.464  0.226
22  2.800   3-                 0.091 -0.259 -0.286 -0.022 -0.016  0.011
23  2.802   3-                 0.081 -0.372 -0.161 -0.021 -0.015  0.017
24  2.805   3-                 0.076 -0.319 -0.210 -0.016 -0.009  0.012
25  2.805   3-                 0.076 -0.210 -0.320 -0.015 -0.009  0.010
26  2.859   3-                -0.308 -0.133 -0.024  0.197  0.212  0.015
27  2.859   3-                -0.308  0.310 -0.469  0.198  0.212  0.017
28  3.092   3-                 0.125 -0.554 -0.489  0.452  0.387  0.000
29  3.218   4-                -0.340 -0.259 -0.074  0.237  0.095  0.014
30  3.280   4-                -0.381 -0.218 -0.234  0.160 -0.012  0.258
31  3.284   4-                -0.379 -0.379  0.019  0.062 -0.012  0.135
32  3.328   4-                -0.368 -0.319 -0.188  0.297  0.162  0.022
33  3.375   3-                -0.688 -0.104  0.192  0.212  0.083  0.023
34  3.382   3-                -0.717 -0.102 -0.013  0.439  0.096  0.020
35  3.423   4-                -0.367 -0.338 -0.194  0.069  0.163  0.311
36  3.430   4-                -0.352 -0.369 -0.111  0.235  0.074  0.068
37  3.431   4-                -0.352 -0.290 -0.141  0.184  0.077  0.120
38  3.439   4-                -0.366 -0.277 -0.200  0.071  0.126  0.269
39  3.463   4-                -0.328 -0.233 -0.258  0.133  0.003  0.159
40  3.464   4-                -0.321 -0.365 -0.023  0.038  0.008  0.195
41  3.470   3-                -0.370 -0.286 -0.129  0.097  0.027  0.203
42  3.470   4-                -0.369 -0.314 -0.228  0.228  0.129  0.227
43  3.489   4-                -0.268 -0.302 -0.185  0.049  0.163  0.218
44  3.489   4-                -0.240 -0.245 -0.269  0.067  0.162  0.207
45  3.509   3-                -0.307 -0.278 -0.267  0.069  0.160  0.306
46  3.510   3-                -0.317 -0.330 -0.185  0.046  0.156  0.283
47  3.517   4-                -0.369 -0.356 -0.245  0.178  0.191  0.309
48  3.529   4-                -0.369 -0.284 -0.224  0.102  0.174  0.296
49  3.533   4-                -0.200 -0.338 -0.137  0.131  0.093  0.111


     1247   1248   1249   1250   1255  1256  1257
0   0.000  0.000  0.000  0.000  0.000 0.000 0.000
1  -0.000  0.025 -0.002 -0.002 -0.000 0.000 0.000
2  -0.001  0.025 -0.002 -0.002 -0.000 0.000 0.000
3   0.015  0.034  0.004  0.004 -0.000 0.000 0.000
4   0.025  0.150  0.101  0.033 -0.000 0.005 0.000
5   0.152  0.023  0.033  0.101 -0.000 0.000 0.005
6   0.002 -0.000 -0.001 -0.001  0.013 0.000 0.000
7   0.024  0.046  0.009  0.008 -0.000 0.000 0.000
8   0.060  0.078  0.018  0.018 -0.000 0.000 0.000
9   0.065  0.074  0.018  0.018 -0.000 0.000 0.000
10  0.089  0.083  0.020  0.020 -0.000 0.000 0.000
11  0.103  0.091  0.006  0.006  0.002 0.000 0.000
12  0.109  0.091  0.005  0.006  0.002 0.000 0.000
13  0.211  0.009  0.017  0.016 -0.000 0.000 0.000
14  0.222  0.001  0.013  0.013 -0.000 0.001 0.001
15  0.121  0.096  0.015  0.014  0.001 0.000 0.000
16  0.120  0.096  0.014  0.015  0.001 0.000 0.000
17  0.008  0.012  0.004  0.004 -0.000 0.000 0.000
18  0.459  0.028 -0.002  0.000 -0.000 0.000 0.001
19  0.032  0.028  0.000 -0.002 -0.000 0.001 0.000
20 -0.000  0.015 -0.002 -0.002  0.005 0.000 0.000
21 -0.001  0.015 -0.002 -0.002  0.005 0.000 0.000
22  0.008  0.001  0.200  0.145 -0.001 0.075 0.053
23  0.010  0.004  0.219  0.112 -0.000 0.085 0.041
24  0.014  0.004  0.134  0.187 -0.000 0.052 0.074
25  0.016  0.004  0.107  0.215 -0.000 0.041 0.085
26  0.002  0.023  0.003  0.004  0.003 0.003 0.003
27  0.001  0.023  0.004  0.004  0.003 0.003 0.003
28  0.002  0.076 -0.000 -0.000  0.001 0.000 0.000
29  0.053  0.216  0.025  0.024  0.004 0.002 0.002
30  0.177  0.090  0.097  0.051 -0.000 0.003 0.009
31  0.344  0.053  0.050  0.098  0.000 0.007 0.003
32  0.115  0.133  0.065  0.067 -0.000 0.007 0.008
33  0.104  0.042  0.020  0.078 -0.000 0.000 0.039
34  0.055  0.102  0.075  0.017 -0.000 0.028 0.000
35  0.235  0.052  0.031  0.028  0.007 0.002 0.002
36  0.167  0.182  0.055  0.042  0.003 0.003 0.002
37  0.144  0.153  0.041  0.055  0.003 0.002 0.003
38  0.236  0.053  0.037  0.040  0.006 0.003 0.003
39  0.220  0.142  0.052  0.080  0.015 0.009 0.005
40  0.252  0.056  0.078  0.049  0.018 0.004 0.011
41  0.231  0.101  0.061  0.059  0.002 0.003 0.003
42  0.244  0.038  0.021  0.021 -0.000 0.003 0.002
43  0.164  0.065  0.011  0.024  0.055 0.001 0.005
44  0.138  0.080  0.020  0.010  0.064 0.004 0.001
45  0.180  0.053  0.027  0.017  0.035 0.003 0.002
46  0.227  0.036  0.018  0.030  0.031 0.002 0.003
47  0.234  0.032  0.009  0.009  0.004 0.002 0.002
48  0.227  0.039  0.015  0.014  0.007 0.002 0.002
49  0.119  0.085  0.012  0.019  0.086 0.002 0.017

-----------------------------------------------------

In [22]:
from westpy.qdet import visualize_correlated_state
for i, state in enumerate(solution2['evcs']):
    en = solution2['evs'][i]
    print(f'i= {i}, en [eV]={en} Deter')
    multiwfc=visualize_correlated_state(state, solution2['norb'], solution2['nelec'], cutoff=10 **(-1))
    print(multiwfc)

i= 0, en [eV]=0.0 Deter
+0.824|0000000000111>|0000000000001>+0.381|0000000000111>|0000000000010>-0.225|0000000000111>|0000000010000>+0.266|0000000001110>|0000000000001>-0.140|0000000010110>|0000000000001>
i= 1, en [eV]=0.20814760326486909 Deter
-0.109|0000000001011>|0000000000001>+0.686|0000000001101>|0000000000001>+0.158|0000000001101>|0000000000010>-0.118|0000000001101>|0000000010000>+0.580|0000000010101>|0000000000001>+0.156|0000000010101>|0000000000010>-0.111|0000000010101>|0000000010000>-0.185|0000000011100>|0000000000001>-0.211|0000010000101>|0000000000001>
i= 2, en [eV]=0.2082544090420467 Deter
+0.686|0000000001011>|0000000000001>+0.158|0000000001011>|0000000000010>-0.118|0000000001011>|0000000010000>+0.109|0000000001101>|0000000000001>+0.580|0000000010011>|0000000000001>+0.156|0000000010011>|0000000000010>-0.111|0000000010011>|0000000010000>-0.185|0000000011010>|0000000000001>-0.211|0000010000011>|0000000000001>
i= 3, en [eV]=1.3521658432433319 Deter
+0.133|0000000000111>|0000000000010>+0.106|0000000001011>|0000000000100>+0.280|0000000001011>|0000000001000>-0.122|0000000001011>|0000010000000>-0.279|0000000001101>|0000000000100>+0.106|0000000001101>|0000000001000>-0.121|0000000001101>|0000001000000>-0.540|0000000001110>|0000000000001>+0.107|0000000001110>|0000000010000>+0.229|0000000010011>|0000000001000>-0.110|0000000010011>|0000010000000>-0.228|0000000010101>|0000000000100>-0.109|0000000010101>|0000001000000>-0.432|0000000010110>|0000000000001>-0.123|0000000010110>|0000000000010>+0.105|0000000010110>|0000000010000>+0.146|0000010000110>|0000000000001>
i= 4, en [eV]=1.4836856949349717 Deter
+0.565|0000000000111>|0000000001000>-0.202|0000000000111>|0000001000000>-0.518|0000000000111>|0000010000000>-0.427|0000000000111>|0000100000000>-0.244|0000000000111>|0001000000000>+0.149|0000000001110>|0000000001000>-0.114|0000000001110>|0000010000000>-0.134|0000000010110>|0000000001000>+0.117|0000000010110>|0000010000000>
i= 5, en [eV]=1.4886756811022983 Deter
+0.566|0000000000111>|0000000000100>+0.518|0000000000111>|0000001000000>-0.202|0000000000111>|0000010000000>+0.244|0000000000111>|0000100000000>-0.427|0000000000111>|0001000000000>+0.149|0000000001110>|0000000000100>+0.114|0000000001110>|0000001000000>-0.134|0000000010110>|0000000000100>-0.117|0000000010110>|0000001000000>
i= 6, en [eV]=1.5044697375425107 Deter
-0.242|0000000000111>|0000000000010>-0.669|0000000000111>|0000000010000>+0.593|0000000000111>|0000000100000>-0.159|0000000000111>|0010000000000>-0.121|0000000001110>|0000000010000>+0.105|0000000001110>|0000000100000>+0.170|0000000010110>|0000000010000>-0.147|0000000010110>|0000000100000>
i= 7, en [eV]=1.6884156577701053 Deter
-0.162|0000000000111>|0000000000010>+0.114|0000000001011>|0000000000100>+0.327|0000000001011>|0000000001000>-0.169|0000000001011>|0000010000000>-0.292|0000000001101>|0000000000100>+0.121|0000000001101>|0000000001000>-0.151|0000000001101>|0000001000000>+0.465|0000000001110>|0000000000001>-0.117|0000000001110>|0000000010000>+0.275|0000000010011>|0000000001000>-0.156|0000000010011>|0000010000000>-0.246|0000000010101>|0000000000100>+0.101|0000000010101>|0000000001000>-0.140|0000000010101>|0000001000000>+0.342|0000000010110>|0000000000001>+0.129|0000000010110>|0000000000010>-0.115|0000000011010>|0000000001000>+0.104|0000000011100>|0000000000100>-0.110|0000010000110>|0000000000001>
i= 8, en [eV]=1.7042246702489412 Deter
+0.414|0000000001011>|0000000000100>+0.216|0000000001011>|0000001000000>-0.105|0000000001011>|0000010000000>-0.125|0000000001011>|0001000000000>-0.420|0000000001101>|0000000001000>+0.103|0000000001101>|0000001000000>+0.221|0000000001101>|0000010000000>+0.127|0000000001101>|0000100000000>+0.347|0000000010011>|0000000000100>+0.195|0000000010011>|0000001000000>-0.122|0000000010011>|0001000000000>-0.351|0000000010101>|0000000001000>+0.200|0000000010101>|0000010000000>+0.123|0000000010101>|0000100000000>-0.136|0000000011010>|0000000000100>+0.138|0000000011100>|0000000001000>-0.114|0000010000011>|0000000000100>+0.115|0000010000101>|0000000001000>
i= 9, en [eV]=1.704276479444951 Deter
-0.403|0000000001011>|0000000001000>+0.104|0000000001011>|0000001000000>+0.212|0000000001011>|0000010000000>+0.124|0000000001011>|0000100000000>-0.430|0000000001101>|0000000000100>-0.225|0000000001101>|0000001000000>+0.104|0000000001101>|0000010000000>+0.129|0000000001101>|0001000000000>-0.337|0000000010011>|0000000001000>+0.191|0000000010011>|0000010000000>+0.120|0000000010011>|0000100000000>-0.360|0000000010101>|0000000000100>-0.204|0000000010101>|0000001000000>+0.125|0000000010101>|0001000000000>+0.132|0000000011010>|0000000001000>+0.142|0000000011100>|0000000000100>+0.111|0000010000011>|0000000001000>+0.118|0000010000101>|0000000000100>
i= 10, en [eV]=1.8047793161127774 Deter
+0.358|0000000001011>|0000000000100>-0.134|0000000001011>|0000000001000>+0.262|0000000001011>|0000001000000>+0.112|0000000001011>|0000100000000>+0.135|0000000001101>|0000000000100>+0.351|0000000001101>|0000000001000>-0.258|0000000001101>|0000010000000>-0.111|0000000001101>|0001000000000>+0.304|0000000010011>|0000000000100>-0.114|0000000010011>|0000000001000>+0.236|0000000010011>|0000001000000>+0.110|0000000010011>|0000100000000>+0.114|0000000010101>|0000000000100>+0.298|0000000010101>|0000000001000>-0.233|0000000010101>|0000010000000>-0.109|0000000010101>|0001000000000>-0.116|0000000011010>|0000000000100>-0.113|0000000011100>|0000000001000>-0.172|0000000100011>|0000000000001>-0.171|0000001000101>|0000000000001>
i= 11, en [eV]=1.9200198700440034 Deter
+0.240|0000000001011>|0000000000001>-0.371|0000000001101>|0000000000001>-0.111|0000000001101>|0000000000010>-0.183|0000000010011>|0000000000001>+0.284|0000000010101>|0000000000001>+0.118|0000000010101>|0000000000010>+0.380|0000000100101>|0000000000001>+0.167|0000000100101>|0000000000010>-0.118|0000000101100>|0000000000001>+0.380|0000001000011>|0000000000001>+0.167|0000001000011>|0000000000010>-0.118|0000001001010>|0000000000001>+0.218|0000010000011>|0000000000001>-0.337|0000010000101>|0000000000001>+0.109|0000100000101>|0000000000001>-0.109|0001000000011>|0000000000001>
i= 12, en [eV]=1.920182347103168 Deter
+0.371|0000000001011>|0000000000001>+0.111|0000000001011>|0000000000010>+0.240|0000000001101>|0000000000001>-0.283|0000000010011>|0000000000001>-0.118|0000000010011>|0000000000010>-0.183|0000000010101>|0000000000001>+0.367|0000000100011>|0000000000001>+0.161|0000000100011>|0000000000010>-0.114|0000000101010>|0000000000001>-0.393|0000001000101>|0000000000001>-0.173|0000001000101>|0000000000010>+0.122|0000001001100>|0000000000001>+0.336|0000010000011>|0000000000001>+0.218|0000010000101>|0000000000001>+0.105|0000100000011>|0000000000001>+0.113|0001000000101>|0000000000001>
i= 13, en [eV]=1.9239926060099053 Deter
+0.116|0000000001011>|0000000000100>+0.113|0000000001101>|0000000001000>+0.556|0000000100011>|0000000000001>+0.248|0000000100011>|0000000000010>-0.135|0000000100011>|0000000010000>-0.154|0000000101010>|0000000000001>+0.539|0000001000101>|0000000000001>+0.241|0000001000101>|0000000000010>-0.131|0000001000101>|0000000010000>-0.149|0000001001100>|0000000000001>+0.162|0000100000011>|0000000000001>-0.158|0001000000101>|0000000000001>
i= 14, en [eV]=1.9987810683542164 Deter
+0.118|0000000000111>|0000000000001>-0.111|0000000000111>|0000000000010>+0.554|0000000100101>|0000000000001>+0.254|0000000100101>|0000000000010>-0.134|0000000100101>|0000000010000>-0.164|0000000101100>|0000000000001>-0.554|0000001000011>|0000000000001>-0.254|0000001000011>|0000000000010>+0.134|0000001000011>|0000000010000>+0.164|0000001001010>|0000000000001>+0.153|0000100000101>|0000000000001>+0.153|0001000000011>|0000000000001>
i= 15, en [eV]=2.0682261537731796 Deter
+0.235|0000000001011>|0000000000001>+0.294|0000000001101>|0000000000001>-0.169|0000000010011>|0000000000001>-0.211|0000000010101>|0000000000001>-0.402|0000000100011>|0000000000001>-0.179|0000000100011>|0000000000010>+0.116|0000000100101>|0000000000001>+0.111|0000000101010>|0000000000001>+0.117|0000001000011>|0000000000001>+0.401|0000001000101>|0000000000001>+0.178|0000001000101>|0000000000010>-0.111|0000001001100>|0000000000001>+0.258|0000010000011>|0000000000001>+0.322|0000010000101>|0000000000001>-0.150|0000100000011>|0000000000001>-0.150|0001000000101>|0000000000001>
i= 16, en [eV]=2.068368503982333 Deter
-0.294|0000000001011>|0000000000001>+0.235|0000000001101>|0000000000001>+0.211|0000000010011>|0000000000001>-0.169|0000000010101>|0000000000001>+0.116|0000000100011>|0000000000001>+0.402|0000000100101>|0000000000001>+0.179|0000000100101>|0000000000010>-0.111|0000000101100>|0000000000001>+0.401|0000001000011>|0000000000001>+0.178|0000001000011>|0000000000010>-0.117|0000001000101>|0000000000001>-0.111|0000001001010>|0000000000001>-0.322|0000010000011>|0000000000001>+0.258|0000010000101>|0000000000001>+0.150|0000100000101>|0000000000001>-0.150|0001000000011>|0000000000001>
i= 17, en [eV]=2.222158544048669 Deter
-0.318|0000000000111>|0000000000001>+0.767|0000000000111>|0000000000010>+0.324|0000000000111>|0000000100000>+0.182|0000000001110>|0000000000010>+0.221|0000000010110>|0000000000001>-0.140|0000000010110>|0000000000010>+0.115|0000000100101>|0000000000001>-0.115|0000001000011>|0000000000001>-0.152|0000010000110>|0000000000001>+0.106|0000100000101>|0000000000001>+0.107|0001000000011>|0000000000001>
i= 18, en [eV]=2.3250138542858982 Deter
-0.173|0000000101001>|0000000000001>-0.151|0000000110001>|0000000000001>-0.665|0000001001001>|0000000000001>-0.142|0000001001001>|0000000000010>-0.577|0000001010001>|0000000000001>-0.149|0000001010001>|0000000000010>-0.156|0000001011000>|0000000000001>-0.214|0000011000001>|0000000000001>
i= 19, en [eV]=2.3252259633235837 Deter
-0.665|0000000101001>|0000000000001>-0.142|0000000101001>|0000000000010>-0.577|0000000110001>|0000000000001>-0.149|0000000110001>|0000000000010>-0.156|0000000111000>|0000000000001>+0.173|0000001001001>|0000000000001>+0.151|0000001010001>|0000000000001>-0.214|0000010100001>|0000000000001>
i= 20, en [eV]=2.4388318634883355 Deter
+0.498|0000000001101>|0000000010000>-0.456|0000000001101>|0000000100000>+0.479|0000000010101>|0000000010000>-0.460|0000000010101>|0000000100000>-0.127|0000000011100>|0000000010000>+0.115|0000000011100>|0000000100000>+0.115|0000010000101>|0000000100000>
i= 21, en [eV]=2.4389308246132204 Deter
+0.498|0000000001011>|0000000010000>-0.456|0000000001011>|0000000100000>+0.479|0000000010011>|0000000010000>-0.460|0000000010011>|0000000100000>-0.127|0000000011010>|0000000010000>+0.115|0000000011010>|0000000100000>+0.115|0000010000011>|0000000100000>
i= 22, en [eV]=2.8003709780753003 Deter
-0.116|0000000100011>|0000000000001>+0.592|0000100000011>|0000000000001>+0.146|0000100000011>|0000000000010>-0.104|0000100000011>|0000000010000>-0.117|0000100001010>|0000000000001>-0.504|0001000000101>|0000000000001>-0.125|0001000000101>|0000000000010>-0.362|0100000000011>|0000000000001>+0.305|1000000000101>|0000000000001>
i= 23, en [eV]=2.802031351315234 Deter
+0.131|0000000100101>|0000000000001>-0.619|0000100000101>|0000000000001>-0.158|0000100000101>|0000000000010>+0.109|0000100000101>|0000000010000>+0.120|0000100001100>|0000000000001>-0.442|0001000000011>|0000000000001>-0.115|0001000000011>|0000000000010>+0.386|0100000000101>|0000000000001>+0.270|1000000000011>|0000000000001>
i= 24, en [eV]=2.804894989747132 Deter
-0.108|0000000001011>|0000000000010>-0.120|0000000010011>|0000000000010>+0.109|0000000100011>|0000000000001>-0.127|0000001000101>|0000000000001>-0.469|0000100000011>|0000000000001>-0.115|0000100000011>|0000000000010>-0.133|0000100000101>|0000000000001>+0.108|0001000000011>|0000000000001>-0.564|0001000000101>|0000000000001>-0.138|0001000000101>|0000000000010>+0.111|0001000001100>|0000000000001>+0.303|0100000000011>|0000000000001>+0.362|1000000000101>|0000000000001>
i= 25, en [eV]=2.8049527779583916 Deter
+0.107|0000000001101>|0000000000010>+0.119|0000000010101>|0000000000010>+0.137|0000001000011>|0000000000001>+0.125|0000100000011>|0000000000001>-0.417|0000100000101>|0000000000001>-0.101|0000100000101>|0000000000010>+0.605|0001000000011>|0000000000001>+0.149|0001000000011>|0000000000010>-0.106|0001000000011>|0000000010000>+0.110|0001000000101>|0000000000001>-0.118|0001000001010>|0000000000001>+0.270|0100000000101>|0000000000001>-0.387|1000000000011>|0000000000001>
i= 26, en [eV]=2.858699913642775 Deter
+0.114|0000000001011>|0000000000010>+0.158|0000000001101>|0000000000001>-0.601|0000000001101>|0000000000010>-0.143|0000000001101>|0000000010000>-0.100|0000000001101>|0000000100000>+0.120|0000000010011>|0000000000010>-0.631|0000000010101>|0000000000010>-0.117|0000000010101>|0000000100000>+0.157|0000000011100>|0000000000010>-0.145|0000010000101>|0000000000001>+0.114|0000010000101>|0000000000010>
i= 27, en [eV]=2.8588056112841 Deter
+0.158|0000000001011>|0000000000001>-0.601|0000000001011>|0000000000010>-0.143|0000000001011>|0000000010000>-0.100|0000000001011>|0000000100000>-0.114|0000000001101>|0000000000010>-0.631|0000000010011>|0000000000010>-0.117|0000000010011>|0000000100000>-0.120|0000000010101>|0000000000010>+0.157|0000000011010>|0000000000010>-0.145|0000010000011>|0000000000001>+0.114|0000010000011>|0000000000010>
i= 28, en [eV]=3.0917859889728847 Deter
+0.882|0000000011001>|0000000000001>+0.180|0000000011001>|0000000000010>-0.106|0000000011001>|0000000010000>-0.369|0000010001001>|0000000000001>
i= 29, en [eV]=3.2179318902760383 Deter
-0.147|0000000000111>|0000000000001>-0.122|0000000001011>|0000000000100>-0.324|0000000001011>|0000000001000>+0.320|0000000001101>|0000000000100>-0.123|0000000001101>|0000000001000>+0.211|0000000001110>|0000000000001>+0.157|0000000010011>|0000000001000>-0.220|0000000010011>|0000010000000>-0.111|0000000010011>|0000100000000>-0.136|0000000010011>|0001000000000>-0.154|0000000010101>|0000000000100>-0.218|0000000010101>|0000001000000>-0.135|0000000010101>|0000100000000>+0.109|0000000010101>|0001000000000>-0.157|0000000010110>|0000000000001>-0.262|0000010000011>|0000000001000>+0.151|0000010000011>|0000010000000>+0.258|0000010000101>|0000000000100>+0.149|0000010000101>|0000001000000>+0.329|0000010000110>|0000000000001>
i= 30, en [eV]=3.280018507188113 Deter
-0.121|0000000000111>|0001000000000>-0.120|0000000000111>|1000000000000>+0.122|0000000100011>|0000000000100>+0.400|0000000100011>|0000000001000>-0.335|0000000100011>|0000010000000>-0.199|0000000100011>|0000100000000>-0.202|0000000100011>|0001000000000>-0.144|0000000100101>|0000000000100>+0.114|0000000100101>|0000000001000>-0.132|0000000100101>|0000001000000>-0.115|0000000100101>|0000100000000>-0.151|0000000100110>|0000000000001>-0.104|0000000101010>|0000000001000>+0.195|0000001000011>|0000000001000>-0.116|0000001000011>|0000001000000>-0.120|0000001000011>|0000010000000>-0.129|0000001000011>|0000100000000>-0.180|0000001000101>|0000000000100>+0.177|0000001000101>|0000000001000>-0.184|0000001000101>|0000001000000>-0.172|0000001000101>|0000100000000>+0.170|0000100000011>|0000000001000>-0.114|0000100000110>|0000000000001>
i= 31, en [eV]=3.2835685618537966 Deter
+0.105|0000000000111>|0000100000000>+0.101|0000000000111>|0100000000000>+0.177|0000000100011>|0000000000100>+0.186|0000000100011>|0000000001000>-0.189|0000000100011>|0000010000000>-0.174|0000000100011>|0001000000000>-0.194|0000000100101>|0000000000100>-0.118|0000000100101>|0000001000000>+0.118|0000000100101>|0000010000000>+0.130|0000000100101>|0001000000000>-0.112|0000001000011>|0000000000100>-0.150|0000001000011>|0000000001000>+0.135|0000001000011>|0000010000000>+0.116|0000001000011>|0001000000000>+0.400|0000001000101>|0000000000100>-0.126|0000001000101>|0000000001000>+0.336|0000001000101>|0000001000000>+0.205|0000001000101>|0000100000000>-0.197|0000001000101>|0001000000000>+0.150|0000001000110>|0000000000001>-0.104|0000001001100>|0000000000100>-0.171|0001000000101>|0000000000100>-0.100|0001000000101>|0000001000000>-0.114|0001000000110>|0000000000001>
i= 32, en [eV]=3.328383254922637 Deter
-0.128|0000000001011>|0000000001000>-0.341|0000000001011>|0000010000000>-0.173|0000000001011>|0000100000000>-0.216|0000000001011>|0001000000000>+0.130|0000000001101>|0000000000100>-0.341|0000000001101>|0000001000000>-0.215|0000000001101>|0000100000000>+0.176|0000000001101>|0001000000000>-0.127|0000000001110>|0000000000001>-0.170|0000000010011>|0000000001000>-0.241|0000000010011>|0000010000000>-0.138|0000000010011>|0000100000000>-0.173|0000000010011>|0001000000000>+0.170|0000000010101>|0000000000100>-0.243|0000000010101>|0000001000000>-0.173|0000000010101>|0000100000000>+0.143|0000000010101>|0001000000000>+0.113|0000000011010>|0000000001000>-0.113|0000000011100>|0000000000100>+0.102|0000000101100>|0000000000001>-0.102|0000001001010>|0000000000001>+0.129|0000010000011>|0000000001000>-0.128|0000010000101>|0000000000100>-0.162|0000010000110>|0000000000001>
i= 33, en [eV]=3.375221849089534 Deter
-0.217|0000000000111>|0000000000100>-0.245|0000000000111>|0001000000000>-0.265|0000000000111>|1000000000000>-0.523|0000000001110>|0000000000100>-0.303|0000000001110>|0000001000000>+0.178|0000000001110>|0000010000000>+0.173|0000000001110>|0001000000000>-0.279|0000000010110>|0000000000100>-0.248|0000000010110>|0000001000000>+0.146|0000000010110>|0000010000000>+0.240|0000000010110>|0001000000000>
i= 34, en [eV]=3.3823750371028294 Deter
+0.183|0000000000111>|0000000001000>+0.216|0000000000111>|0000100000000>+0.225|0000000000111>|0100000000000>+0.534|0000000001110>|0000000001000>-0.184|0000000001110>|0000001000000>-0.318|0000000001110>|0000010000000>-0.189|0000000001110>|0000100000000>+0.306|0000000010110>|0000000001000>-0.152|0000000010110>|0000001000000>-0.262|0000000010110>|0000010000000>-0.242|0000000010110>|0000100000000>
i= 35, en [eV]=3.4226022330030275 Deter
-0.143|0000000001101>|0000000001000>-0.113|0000000010101>|0000010000000>-0.108|0000000100011>|0000000000100>+0.355|0000000100011>|0000000010000>-0.316|0000000100011>|0000000100000>+0.142|0000000100101>|0000000001000>-0.109|0000000100101>|0000010000000>-0.110|0000000100101>|0000100000000>-0.127|0000000101010>|0000000000001>+0.139|0000001000011>|0000000001000>-0.108|0000001000011>|0000010000000>-0.106|0000001000011>|0000100000000>+0.147|0000001000101>|0000000000100>+0.363|0000001000101>|0000000010000>-0.323|0000001000101>|0000000100000>+0.115|0000001000101>|0000001000000>-0.107|0000001000101>|0001000000000>-0.137|0000001001100>|0000000000001>-0.112|0000010000101>|0000000001000>
i= 36, en [eV]=3.4295578808258367 Deter
+0.276|0000000001011>|0000000001000>-0.137|0000000001011>|0000010000000>+0.277|0000000001101>|0000000000100>+0.135|0000000001101>|0000001000000>-0.170|0000000010011>|0000000001000>+0.191|0000000010011>|0000010000000>+0.116|0000000010011>|0000100000000>+0.114|0000000010011>|0001000000000>-0.168|0000000010101>|0000000000100>-0.191|0000000010101>|0000001000000>-0.115|0000000010101>|0000100000000>+0.116|0000000010101>|0001000000000>-0.155|0000000100011>|0000000001000>+0.110|0000000100011>|0000010000000>+0.130|0000000100011>|0000100000000>-0.253|0000001000101>|0000000001000>+0.243|0000001000101>|0000010000000>+0.161|0000001000101>|0000100000000>+0.153|0000001000101>|0001000000000>+0.231|0000010000011>|0000000001000>-0.156|0000010000011>|0000010000000>+0.232|0000010000101>|0000000000100>+0.157|0000010000101>|0000001000000>
i= 37, en [eV]=3.430888556315223 Deter